config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :rooms

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
	
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   validates :username, uniqueness: true, presence: true
   validates :email, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!

before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_url(user)
	  gravatar_id = Digest::MD5::hexdigest(user.email).downcase
	  url = "https://gravatar.com/avatar/#{gravatar_id}.png"
	end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom ">
	<ul class="navbar-nav ml-auto">
    <li class="nav-item active">
      <%= link_to "About", static_pages_about_path, :class => "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Help", static_pages_help_path, :class => "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <%= link_to "Devise Base", root_path, :class => "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user %>
    <div class="dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <img class="avatar" src="<%= gravatar_url(current_user) %>">
        <%= current_user.username %>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  <% end %>
</nav>  

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
   <title>DeviseBase</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <%= render partial: 'layouts/navigation_bar' %>
            <%= yield %>
          <%= render partial: 'layouts/footer' %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/rooms/index.html.erb
<h1>Room Index</h1>

app/views/static_pages/about.html.erb
<h1>About this application</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>